### ISSUE TITLE
Requerimientos iniciales

### ISSUE THREAD

**Issue by DanielJimenezA** [DanielJimenezA/linuxWebDocker#1]
Requerimientos de Hardware:

- [x] Switch
- [x] Tres cables Ethernet
- [x] Tres computadoras

Requerimientos de Software:

- [x] Packet Tracer
- [x] Docker
- [x] Distribución linux Centos, RedHat , Debian (¿Cuál será?)

**Comment by Jorel254** [comment]
Yo digo que sigamos con Centos
